# Command to run from ~/projekty/praca_magisterska/application/unity_mla_environment:
# mlagents-learn MasterRacingEnvs/Assets/MyTrainingConfig/RaceTrack_2_SAC.yaml --run-id=RaceTrack_2_SAC --results-dir=MasterRacingEnvs/Assets/MyTrainingResults

engine_settings:
  width: 240 # default = 84
  height: 135 # default = 84
  quality_level: 5 # default = 5
  time_scale: 20 # default = 20
  target_frame_rate: -1 # default = -1
  capture_frame_rate: 60 # default = 60
  no_graphics: false
torch_settings:
  device: cuda # default = cpu
behaviors:
  CarAgentBehaviour:
    trainer_type: sac
    summary_freq: 20000 # default = 50000
    time_horizon: 256 # default = 64, typical range: 32 - 2048
    max_steps: 5000000 # default = 500000, typical range: 5e5 - 1e7
    keep_checkpoints: 10 # default = 5
    checkpoint_interval: 500000 # default = 500000
    threaded: true # default = false
    hyperparameters:
      # Hyperparameters common to PPO and SAC
      #learning_rate: 0.0003 # default = 3e-4, typical range: 1e-5 - 1e-3
      batch_size: 512 # typical range: 128 - 1024
      buffer_size: 50000 # default = 50000, typical range: 50000 - 1000000
      learning_rate_schedule: constant
      # SAC-specific hyperparameters
      buffer_init_steps: 1000 # default = 0, typical range: 1000 - 10000
      init_entcoef: 1.0 # default = 1.0, typical range: 0.5 - 1.0
      #save_replay_buffer: true # default = false
      tau: 0.005 # default = 0.005, typical range: 0.005 - 0.01
      steps_per_update: 1 # default = 1, typical range: 1 - 20
    network_settings:
      hidden_units: 128 # default = 128, typical range: 32 - 512
      num_layers: 2 # default = 2, typical range: 1 - 3
      normalize: true # default = false
      vis_encode_type: nature_cnn # default = simple, all values: simple, nature_cnn, resnet, match3, fully_connected
      conditioning_type: none # default = hyper, all values: hyper, none
    reward_signals:
      extrinsic:
        strength: 1.0 # default = 1.0
        gamma: 0.99 # default = 0.99, typical range: 0.8 - 0.995. Must be smaller than 1.
      #curiosity:
        #strength: ?? # default = 1.0, typical range: 0.001 - 0.1
        #gamma: ?? # default = 0.99, typical range: 0.8 - 0.995
        #network_settings:
          #hidden_units: ?? # default = 128, typical range: 64 - 256
          #num_layers: ?? # default = 2, typical range: 1 - 3
          #normalize: ?? # default = false
          #vis_encode_type: ?? # default = simple, all values: simple, nature_cnn, resnet, match3, fully_connected
          #conditioning_type: ?? # default = hyper, all values: hyper, none
        #learning_rate: ?? # default = 3e-4, typical range: 1e-5 - 1e-3
      #gail:
        #strength: ?? # default = 1.0, typical range: 0.01 - 1.0
        #gamma: ?? # default = 0.99, typical range: 0.8 - 0.9
        #demo_path: ?? # Required, no default
        #network_settings:
          #hidden_units: ?? # default = 128, typical range: 64 - 256
          #num_layers: ?? # default = 2, typical range: 1 - 3
          #normalize: ?? # default = false
          #vis_encode_type: ?? # default = simple, all values: simple, nature_cnn, resnet, match3, fully_connected
          #conditioning_type: ?? # default = hyper, all values: hyper, none
        #learning_rate: ?? # Optional, default = 3e-4, typical range: 1e-5 - 1e-3
        #use_actions: ?? # default = false
        #use_vail: ?? # default = false
    #behavioral_cloning:
      #demo_path: ?? # Required, no default
      #strength: ?? # default = 1.0, typical range: 0.1 - 0.5
      #steps: ?? # default = 0
      #batch_size: ?? # default = batch_size of trainer, typical range: 512 - 5120
      #num_epoch: ?? # default = num_epoch of trainer, typical range: 3 - 10
      #samples_per_update: ?? # default = 0, typical range: buffer_size
